function value(id){return parseFloat(document.getElementById(id).value)}
function format(value,digits=4){if(!Number.isFinite(value))return"—";return Number(value.toFixed(digits)).toString()}
function showResult(id,html,error=false){const el=document.getElementById(id);el.innerHTML=html;el.classList.toggle("error",error)}
function calculateGrowth(){const x1=value("growthX1"),x2=value("growthX2"),t1=value("growthT1"),t2=value("growthT2"),dt=t2-t1;if(!(x1>0&&x2>0&&dt>0)){showResult("growthResult","<strong>Check inputs: X₁ and X₂ must be > 0 and t₂ must be greater than t₁.</strong>",true);return}const mu=(Math.log(x2)-Math.log(x1))/dt,doubling=mu>0?Math.log(2)/mu:NaN;showResult("growthResult",`<strong>μ = ${format(mu,4)} h⁻¹</strong><strong>Doubling time = ${format(doubling,3)} h</strong>`)}
function calculateYxs(){const x1=value("yxsX1"),x2=value("yxsX2"),s1=value("yxsS1"),s2=value("yxsS2"),consumed=s1-s2;if(!(consumed>0)){showResult("yxsResult","<strong>S₁ must be greater than S₂.</strong>",true);return}showResult("yxsResult",`<strong>Yx/s = ${format((x2-x1)/consumed,4)} g/g</strong>`)}
function calculateYps(){const p1=value("ypsP1"),p2=value("ypsP2"),s1=value("ypsS1"),s2=value("ypsS2"),consumed=s1-s2;if(!(consumed>0)){showResult("ypsResult","<strong>S₁ must be greater than S₂.</strong>",true);return}showResult("ypsResult",`<strong>Yp/s = ${format((p2-p1)/consumed,4)} g/g</strong>`)}
function calculateSubstrate(){const s0=value("substrateInitial"),sf=value("substrateFinal");if(!(s0>0)){showResult("substrateResult","<strong>Initial substrate must be greater than 0.</strong>",true);return}showResult("substrateResult",`<strong>Substrate consumption = ${format(((s0-sf)/s0)*100,2)} %</strong>`)}
function calculateQp(){const p1=value("qpP1"),p2=value("qpP2"),t1=value("qpT1"),t2=value("qpT2"),dt=t2-t1;if(!(dt>0)){showResult("qpResult","<strong>t₂ must be greater than t₁.</strong>",true);return}showResult("qpResult",`<strong>Qp = ${format((p2-p1)/dt,4)} g/L/h</strong>`)}
function calculateQx(){const x1=value("qxX1"),x2=value("qxX2"),t1=value("qxT1"),t2=value("qxT2"),dt=t2-t1;if(!(dt>0)){showResult("qxResult","<strong>t₂ must be greater than t₁.</strong>",true);return}showResult("qxResult",`<strong>Qx = ${format((x2-x1)/dt,4)} g/L/h</strong>`)}
function calculateGlucoseCarbon(){const glucose=value("glucoseMass");if(!(glucose>=0)){showResult("glucoseCarbonResult","<strong>Enter a valid glucose mass.</strong>",true);return}showResult("glucoseCarbonResult",`<strong>Carbon = ${format(glucose*0.40002,3)} g C</strong>`)}
function calculateCO2Carbon(){const volume=value("co2Volume"),vm=value("molarVolume");if(!(volume>=0&&vm>0)){showResult("co2CarbonResult","<strong>CO₂ volume must be ≥ 0 and Vm must be > 0.</strong>",true);return}showResult("co2CarbonResult",`<strong>Carbon = ${format((volume/vm)*12.011,3)} g C</strong>`)}
document.addEventListener("DOMContentLoaded",()=>{calculateGrowth();calculateYxs();calculateYps();calculateSubstrate();calculateQp();calculateQx();calculateGlucoseCarbon();calculateCO2Carbon()});
